<?php

declare(strict_types=1);

namespace NgarakDev\Modularization\Support;

use Illuminate\Filesystem\Filesystem;
use NgarakDev\Modularization\Module;

/**
 * Caches discovered module metadata to avoid filesystem scans on every boot.
 *
 * The cache is a JSON file stored at bootstrap/cache/modules.php.
 * In production use 'php artisan module:cache' to build the cache.
 * Use 'php artisan module:clear' to invalidate it.
 */
final class ModuleCache
{
    private string $cachePath;

    public function __construct(
        private readonly Filesystem $files,
        string $bootstrapPath,
    ) {
        $this->cachePath = $bootstrapPath.'/cache/modules.php';
    }

    /**
     * Whether a valid cache file exists.
     */
    public function isCached(): bool
    {
        return $this->files->exists($this->cachePath);
    }

    /**
     * Load modules from cache.
     *
     * @return array<string, Module>|null Returns null if cache is missing or corrupt.
     */
    public function load(): ?array
    {
        if (! $this->isCached()) {
            return null;
        }

        try {
            $data = require $this->cachePath;

            if (! is_array($data)) {
                return null;
            }

            $modules = [];
            foreach ($data as $name => $moduleData) {
                $modules[$name] = new Module(
                    name: $moduleData['name'],
                    path: $moduleData['path'],
                    enabled: $moduleData['enabled'],
                    namespace: $moduleData['namespace'],
                    version: $moduleData['version'],
                    description: $moduleData['description'],
                    requires: $moduleData['requires'],
                );
            }

            return $modules;
        } catch (\Throwable) {
            return null;
        }
    }

    /**
     * Write modules to the cache file.
     *
     * @param  array<string, Module>  $modules
     */
    public function write(array $modules): void
    {
        $data = [];
        foreach ($modules as $name => $module) {
            $data[$name] = $module->toArray();
        }

        $export = var_export($data, true);
        $content = "<?php\n\n// This file is auto-generated by 'php artisan module:cache'.\n// Do not edit manually.\n\nreturn {$export};\n";

        $cacheDir = dirname($this->cachePath);
        if (! $this->files->isDirectory($cacheDir)) {
            $this->files->makeDirectory($cacheDir, 0755, true);
        }

        $this->files->put($this->cachePath, $content);
    }

    /**
     * Remove the cache file.
     */
    public function clear(): bool
    {
        if ($this->files->exists($this->cachePath)) {
            $this->files->delete($this->cachePath);

            return true;
        }

        return false;
    }

    public function getCachePath(): string
    {
        return $this->cachePath;
    }
}
