<?php

declare(strict_types=1);

return [

    /*
    |--------------------------------------------------------------------------
    | Modules Directory
    |--------------------------------------------------------------------------
    |
    | Path where modules are stored, relative to the application base path.
    | Directory names must stay inside this path; `..` segments are rejected.
    |
    */
    'modules_path' => env('MODULES_PATH', 'modules'),

    /*
    |--------------------------------------------------------------------------
    | Module Namespace
    |--------------------------------------------------------------------------
    |
    | Root PHP namespace for generated and discovered modules.
    |
    */
    'namespace' => env('MODULES_NAMESPACE', 'Modules'),

    /*
    |--------------------------------------------------------------------------
    | Default Module Directories
    |--------------------------------------------------------------------------
    |
    | Directories created inside each new module. Existing modules are not
    | rewritten when this list changes.
    |
    */
    'directories' => [
        'Config',
        'Console',
        'Database/Factories',
        'Database/Migrations',
        'Database/Seeders',
        'Events',
        'Http/Controllers',
        'Http/Controllers/API',
        'Http/Middleware',
        'Http/Requests',
        'Jobs',
        'Listeners',
        'Livewire',
        'Models',
        'Policies',
        'Providers',
        'Repositories',
        'Repositories/Interfaces',
        'Resources/assets/css',
        'Resources/assets/js',
        'Resources/lang',
        'Resources/views',
        'Routes',
        'Services',
        'Services/Interfaces',
        'Tests/Feature',
        'Tests/Unit',
    ],

    /*
    |--------------------------------------------------------------------------
    | Auto-register Routes
    |--------------------------------------------------------------------------
    |
    | When true, the package loads each enabled module's web, API, and Livewire
    | route files. Set to false if modules register routes from their own
    | service providers.
    |
    | Key kept as auto_register_controllers for backwards compatibility.
    |
    */
    'auto_register_controllers' => true,
    'auto_register_providers' => true,

    /*
    |--------------------------------------------------------------------------
    | Auto-Register Routes
    |--------------------------------------------------------------------------
    |
    | When true, PHP classes under a module's Livewire directory that extend
    | Livewire\Component are registered. Ignored when Livewire is not installed.
    |
    */
    'auto_register_livewire' => true,

    /*
    |--------------------------------------------------------------------------
    | Scaffolding
    |--------------------------------------------------------------------------
    |
    | Repository and service classes are optional. They are generated by
    | default because that is the package's original workflow, but you can
    | disable them globally or pass --no-repository / --no-service.
    |
    */
    'scaffold' => [
        'repositories' => true,
        'services' => true,
    ],

    /*
    |--------------------------------------------------------------------------
    | Repository Pattern
    |--------------------------------------------------------------------------
    |
    | Kept for backwards compatibility. Prefer scaffold.repositories.
    |
    */
    'enforce_repository_pattern' => true,

    /*
    |--------------------------------------------------------------------------
    | Module Cache
    |--------------------------------------------------------------------------
    |
    | Production applications should run `php artisan module:cache` during
    | deploy so boot does not scan the modules directory. When `enabled` is
    | null, caching is used automatically in the production environment if
    | a cache file exists.
    |
    */
    'cache' => [
        'enabled' => null,
        'path' => 'bootstrap/cache/modules.php',
    ],

    /*
    |--------------------------------------------------------------------------
    | Dependencies
    |--------------------------------------------------------------------------
    |
    | When fail_on_missing is true, booting an enabled module whose `requires`
    | list points at a missing module throws a ModuleDependencyException.
    |
    */
    'dependencies' => [
        'fail_on_missing' => false,
    ],

    /*
    |--------------------------------------------------------------------------
    | Disabled Modules
    |--------------------------------------------------------------------------
    |
    | Disabled modules are skipped during registration when true.
    |
    */
    'skip_disabled' => true,

    /*
    |--------------------------------------------------------------------------
    | Composer Autoload
    |--------------------------------------------------------------------------
    |
    | When creating the first module, add the modules namespace to composer.json.
    |
    */
    'update_composer' => true,
];
