<?php

declare(strict_types=1);

namespace NgarakDev\Modularization;

use Illuminate\Filesystem\Filesystem;
use NgarakDev\Modularization\Support\ModuleName;

/**
 * Reads and writes a module's machine-readable contract.
 *
 * Prefers module.json, then falls back to Config/config.php for
 * modules generated by earlier versions of the package.
 */
final class ModuleManifest
{
    public function __construct(
        private readonly Filesystem $files,
        private readonly ModulePathResolver $paths,
        private readonly ModuleConfiguration $configuration,
    ) {}

    /**
     * @return array<string, mixed>
     */
    public function read(string $modulePath, string $name): array
    {
        $jsonPath = $this->paths->join($modulePath, 'module.json');

        if ($this->files->isFile($jsonPath)) {
            return $this->normalize($this->decodeJson($jsonPath), $name, $modulePath, 'module.json');
        }

        $configRelative = $this->paths->firstExistingFile($modulePath, [
            'Config/config.php',
            'config/config.php',
        ]);

        if ($configRelative !== null) {
            $configPath = $this->paths->join($modulePath, $configRelative);
            /** @var mixed $config */
            $config = $this->files->getRequire($configPath);

            if (is_array($config)) {
                return $this->normalize($config, $name, $modulePath, $configRelative);
            }
        }

        return $this->normalize([], $name, $modulePath, null);
    }

    /**
     * @param  array<string, mixed>  $data
     */
    public function write(string $modulePath, array $data): string
    {
        $path = $this->paths->join($modulePath, 'module.json');
        $encoded = json_encode($data, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES)."\n";

        $this->files->ensureDirectoryExists(dirname($path));
        $this->files->put($path, $encoded);

        return $path;
    }

    /**
     * @param  array<string, mixed>  $raw
     * @return array<string, mixed>
     */
    private function normalize(array $raw, string $name, string $modulePath, ?string $manifestPath): array
    {
        $namespace = $this->configuration->namespace();
        $parsed = ModuleName::parse($name);

        $requires = $raw['requires'] ?? $raw['dependencies'] ?? [];
        if (! is_array($requires)) {
            $requires = [];
        }

        $parsedRequires = ModuleRequirement::parseList($requires);

        $lifecycle = (string) ($raw['lifecycle'] ?? '');
        $enabled = (bool) ($raw['enabled'] ?? true);
        if ($lifecycle === '') {
            $lifecycle = $enabled ? 'enabled' : 'disabled';
        }

        return [
            'name' => (string) ($raw['name'] ?? $parsed->studly()),
            'namespace' => (string) ($raw['namespace'] ?? $namespace.'\\'.$parsed->studly()),
            'provider' => (string) ($raw['provider'] ?? $namespace.'\\'.$parsed->studly().'\\Providers\\'.$parsed->studly().'ServiceProvider'),
            'version' => (string) ($raw['version'] ?? '1.0.0'),
            'description' => (string) ($raw['description'] ?? $parsed->studly().' module'),
            'enabled' => $enabled,
            'lifecycle' => $lifecycle,
            'requires' => array_keys($parsedRequires),
            'requirement_constraints' => array_map(
                static fn (ModuleRequirement $requirement): string => $requirement->constraint,
                $parsedRequires
            ),
            'manifest_path' => $manifestPath,
            'path' => $modulePath,
        ];
    }

    /**
     * @return array<string, mixed>
     */
    private function decodeJson(string $path): array
    {
        $contents = $this->files->get($path);
        $decoded = json_decode($contents, true);

        if (! is_array($decoded)) {
            return [];
        }

        return $decoded;
    }
}
